backend:
  name: github
  repo: ChromTules/miyawakiforestbelmont.github.io
  branch: main

media_folder: src/assets/images
public_folder: /assets/images

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "src/content/hero.json"
        fields:
          - label: "Main Title"
            name: "title"
            widget: "string"
            default: "Growing Native Forests, One Tree at a Time"
          - label: "Subtitle"
            name: "subtitle"
            widget: "text"
          - label: "Hero Image"
            name: "hero_image"
            widget: "image"
            required: false
          - label: "Call to Action Button Text"
            name: "cta_text"
            widget: "string"
          - label: "Call to Action URL"
            name: "cta_url"
            widget: "string"

  - name: "content"
    label: "Site Content"
    files:
      - name: "mission"
        label: "Mission & Benefits"
        file: "src/content/mission.json"
        fields:
          - label: "Mission Statement"
            name: "mission"
            widget: "markdown"
          - label: "Benefits"
            name: "benefits"
            widget: "list"
            field:
              label: "Benefit"
              name: "text"
              widget: "string"

      - name: "contact"
        label: "Contact Information"
        file: "src/content/contact.json"
        fields:
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Website URL"
            name: "website"
            widget: "string"
          - label: "Volunteer Form URL"
            name: "volunteer_form"
            widget: "string"
          - label: "Donation URL"
            name: "donation_url"
            widget: "string"

  - name: "updates"
    label: "Project Updates"
    folder: "src/content/updates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Content"
        name: "body"
        widget: "markdown"
